INHERIT: redirects.yml
nav:
  - Quickstart: index.md
  - Getting Started:
      - Getting Started: getting_started/index.md
      - Namespaces: getting_started/namespaces.md
      - Flows & States: getting_started/states.md
      - Transforms & JQ/JS: getting_started/transforms.md
      - Input & Transitions: getting_started/transitions.md
      - Conditional Transitions: getting_started/conditional-transitions.md
      - Introduction to Functions: getting_started/functions-intro.md
      - Scheduling: getting_started/scheduling.md
      - Subflows: getting_started/subflows.md
      - Persistent Data: getting_started/persistent-data.md
      - Error Handling: getting_started/error-handling.md
      - Events in Direktiv: getting_started/events.md
      - Validating Input: getting_started/validating.md
      - Secrets & Registries: getting_started/secrets-registries.md
      - Advanced Topics:
          - Timeouts: getting_started/advanced/timeout.md 
          - Custom Functions: getting_started/advanced/making-functions.md
          - Metadata: getting_started/advanced/metadata.md 
  - Installation:
      - Install: installation/index.md
      - Kubernetes: installation/kubernetes.md
      - Linkerd: installation/linkerd.md
      - Database: installation/database.md
      - Direktiv: installation/direktiv.md
      - Quick Install: installation/summary.md
  - Specification:
      - Workflow YAML:
          - Workflow: spec/workflow-yaml/workflow.md
          - Functions: spec/workflow-yaml/functions.md
          - Triggers / Starts: spec/workflow-yaml/starts.md
          - Timeouts: spec/workflow-yaml/timeouts.md
          - Actions: spec/workflow-yaml/actions.md
          - Errors: spec/workflow-yaml/errors.md
          - Logging: spec/workflow-yaml/logging.md
          - Instance Metadata: spec/workflow-yaml/metadata.md
          - States:
              - States: spec/workflow-yaml/states.md
              - action: spec/workflow-yaml/action.md
              - consumeEvent: spec/workflow-yaml/consume-event.md
              - delay: spec/workflow-yaml/delay.md
              - error: spec/workflow-yaml/error.md
              - eventsAnd: spec/workflow-yaml/events-and.md
              - eventsXor: spec/workflow-yaml/events-xor.md
              - foreach: spec/workflow-yaml/foreach.md
              - generateEvent: spec/workflow-yaml/generate-event.md
              - getter: spec/workflow-yaml/getter.md
              - noop: spec/workflow-yaml/noop.md
              - parallel: spec/workflow-yaml/parallel.md
              - setter: spec/workflow-yaml/setter.md
              - switch: spec/workflow-yaml/switch.md
              - validate: spec/workflow-yaml/validate.md
      - Instance Data:
          - Instance Data: spec/instance-data/instance-data.md
          - Input: spec/instance-data/input.md
          - Output: spec/instance-data/output.md
          - Transforms: spec/instance-data/transforms.md
          - Structured JX: spec/instance-data/structured-jx.md
          - Security: spec/instance-data/security.md
      - Variables:
          - Variables: spec/variables/variables.md
          - System: spec/variables/system.md
  - API: api.md
  - Development:
      - Standalone Environment: environment/direktiv-development-environment.md
      - direktivctl: environment/cli.md
      - Git Sync: environment/git.md
  - Examples:
    - AWS Examples: examples/aws.md
    - Conditional State: examples/conditional-states.md
    - Counter: examples/counter-persistent-data.md
    - Cron: examples/cron.md
    - Foreach : examples/foreach.md
    - Greeting Example: examples/greeting.md
    - Event-based Workflow: examples/greeting-event-listener.md
    - Convert Input: examples/input-convert.md
    - Request API: examples/request-external-api.md
    - Scripting: examples/scripting.md
    - Solving Math Expressions: examples/solving-math-expressions.md
    - Subflows: examples/subflows.md
    - Variable Mime Type Example: examples/variable-mime-type.md
    - Variable Scopes: examples/variables.md
  - Events:
      - General: events/index.md
      - Filter: events/filter.md
      - Cloud:
          - General: events/cloud/index.md
          - Amazon: events/cloud/amazon.md
          - Azure: events/cloud/azure.md
          - Google Cloud Platform: events/cloud/gcp.md
      - Knative:
          - Eventing: events/knative/knative.md
          - Kafka Example: events/knative/example.md
          - VMware Example: events/knative/vmware.md
