get:
  tags:
    - gateway
  summary: Get all routes
  parameters:
    - $ref: '../parameters.yaml#/namespace'
    - in: query
      name: path
      schema:
        type: string
      description: Filter result by path string
  responses:
    "200":
      description: Routes for gateway in the namespace
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '../objects.yaml#/route'