name: Update Docs
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'release tag, e.g. v.0.5.0'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
          persist-credentials: false
          fetch-depth: 0
          branch: master
    - name: run generate-docs
      run: |
        echo "Updating docs for release ${{ github.event.inputs.release}}"
        make install-deps
        make update-api
    - name: Commit & Push Changes
      uses: actions-js/push@master
      with:
        branch: master
        github_token: ${{ secrets.TOKEN_GITHUB }}